### PR TITLE
Fix a typo in pyipmi.__init__.py to report errors correctly

### PR DESCRIPTION
**Pull request by szaher**
if an error happened I wont be reported as this type will give another error

### CODE REVIEW

**Comment by szaher** [comment]
for the msgs, it's not imported in this file ... 
also import functools is unused

**Comment by szaher** [comment]
for the interface_type ( which should be interface but for not to confuse others I made it interface_type) we need to be able to pass it to the ipmitool interface, can we at least merge the 3rd commit ??

**Comment by szaher** [comment]
Can we merge this change asap please ?

**Comment by hthiery** [comment]
I just implemented the feature you requested and wrote some tests. Please give feedback if this fulfills your needs.

**Comment by szaher** [comment]
Sure, will test that, but will it be available soon in PYPI ?

**Comment by szaher** [comment]
is it only lan and lanplus are supported by this library ?

**Comment by hthiery** [comment]
currently yes ... what interface type do you like to support?


2015-12-16 11:22 GMT+01:00 Saad Zaher <notifications@github.com>:

**Pull request closed without merging**
