### PR TITLE
Fix parsing of maximum current output in power module capability record

### PR DESCRIPTION
**Pull request by lyodaom**

### CODE REVIEW

**Comment by hthiery** [comment]
Hi, thanks for that fix. Do you have an example fru binary file that we could include for unit testing?

**Comment by lyodaom** [comment]
Done, the unit test added uses FRU data from a power module

**Comment by hthiery** [comment]
Looks good so far. Would you please add your "Signed-off-by" tag.

**Comment by lyodaom** [comment]
Done

**Comment by lyodaom** [comment]
I think I added the sign-off-by tag but it doesn't contain a signature, is that OK for you? or do you also require the commit to have the GPG signature?

**Comment by mwalle** [comment]
Am 2021-10-04 10:52, schrieb Emilio PJ:
> I think I added the sign-off-by tag but it doesn't contain a
> signature, is that OK for you? or do you also require the commit to
> have the GPG signature?

No, only your SoB is needed. No need for a GPG signature.

-michael

**Comment by lyodaom** [comment]
Thanks for clarifying

**Pull request merged**
